### PR TITLE
Fix ping location when pinging from different zone and using global coordinates

### PR DESCRIPTION
**Pull request by yachoor**
Coordinates are converted from Global to Local on current map, causing wrong ping locations if it's not the same map.
This fixes the pings by calculating local coordinates after changing the map.
The menu option will still display some random coordinates when on different map, but it's not that important

### CODE REVIEW

**Comment by yachoor** [comment]
New libGPS API allows to query for coordinates on target map without switching to it first.
Now the tooltip coordinates are also correct

**Comment by Sharlikran** [comment]
Should be addressed in this commit: https://github.com/ESOUIMods/LoreBooks/commit/23c9386867cb57ba28f88aaeb5326dbeb352bb56

**Comment by Sharlikran** [comment]
@yachoor There was a map you had with all the Map IDs for it with red lines drawn on it, where did that go? Can you post that again please?

**Comment by Sharlikran** [comment]
image

I have those recorded but no idea where mapId 1973 is unless there is another place with that name from an older part of the game.

Also if someone said "The Chapel" where would that be, exactly? Supposedly there is a copy of the book by the chapel rather then in the Adytum itself after you complete the quest.

**Comment by yachoor** [comment]
Ah, I think you already found it, but it was [here](https://github.com/ESOUIMods/LoreBooks/pull/5#issuecomment-1359759534)
And the Adytum was not marked there, but it's the area in that building on north-east side. I'd call it a chapel - looks like it.
I think it wasn't available after quest originally, but they changed it and now it is

**Pull request closed without merging**
