### PR TITLE
Eidetic updates

### PR DESCRIPTION
**Pull request by yachoor**

### CODE REVIEW

**Comment by yachoor** [comment]
I've added all entries from comments section from one before the marking post - 05/13/22, 09:40 up to 12/18/2022, 17:44.
I've also added missing dungeon entrance to all new (and some old) entries where possible (some were available only through portal during quest) and zone to entries in cities (except Fargrave - pin's show up in wrong places if I use zm there).
I deleted old entries for The Folly of Isolation* in Circus of Cheerful Slaughter (some had over 70 pins, completely out of the map or in the walls, the data was there from the first commit) and left only newly reported ones (they showed in right spots on the map).
Also changed some pins that were showing over cities on zone map, but not on the city map, so they showed on both, but there's lots more of those to fix.
And fixed Harborage pins for Daggerfall and Ebonheart - all had Aldmeri map :)

**Comment by yachoor** [comment]
I could probably split it into 2 or more merge requests - maybe one with only new books and another with updates if it makes it easier?

**Comment by Sharlikran** [comment]
No this is fine, I appreciate it.

**Comment by Sharlikran** [comment]
I will have to look at things but I was marking things in the forums that I had the data in a file to enter at a later time. I had not entered it I was just keeping track. This will still be a big help though. I just have to review the commits, and make sure they are single line and I can edit them if not. The single line is how I know it's updated and not from the initial database overhaul.

**Comment by yachoor** [comment]
I think I added almost all of new entries as single line unless it was underground where I usually did it in 2 lines - second with zx, zy, zm for easy copying to other books in same place,
But I also updated many existing entries with zm information - I did not touch formatting on those and I did not run to the books, just dungeon/delve entrances and later checked the map display.
Sorry, wanted to take some of that work of your back - I know you're busy with all those other wonderful addons

**Pull request merged**
